### ISSUE TITLE
hi,thanks zakar,I can't find any place to generate id and token

### ISSUE THREAD

**Issue by lankii** [zakaryaasadi/api_for_nopcommerce#1]
I installed it successfully, but I can't find any place to generate id and token. I hope to connect to another software through api. Please teach me how. Visit api? xxxx.com/api/?

i used nop4.3

**Comment by zakaryaasadi** [comment]
Hello @lankii 

please check the documentation

https://github.com/zakaryaasadi/api_for_nopcommerce/blob/main/Token.md
