### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by Prateek58** [zakaryaasadi/api_for_nopcommerce#2]
Thanks for the contribution,
It will be nice if it have document for apis

**Comment by zakaryaasadi** [comment]
Thanks @Prateek58 

Already put documentation

**Comment by Prateek58** [comment]
Hi,
the document is not complete, for example "orders" api documents are blank.
https://github.com/SevenSpikes/api-plugin-for-nopcommerce/blob/nopCommerce_4.20/Orders.md
Regards,
thehulk58
